baseURL = 'http://127.0.0.1'
languageCode = 'en-US'
title = 'Hello World'
theme = 'drew.x64.onl'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30