baseURL = 'https://drew.x64.onl/'
languageCode = 'en-us'
title = "Aloha World"
theme = 'x64'

[params]
  description = "I'm Drew: Jack of Cyber"
  keywords = "cybersecurity, cybersecurity engineer, drew, homepage, information security, jack of cyber, portfolio, privacy, security, x64"

  [params.author]
    email = "drew@x64.onl"
    name = "Drew"
    url = "https://drew.x64.onl"