baseURL = 'https://drew.x64.onl/'
languageCode = 'en-us'
title = "Drew's Lab"
theme = 'x64'

[params]
  description = "Hi, I'm Drew."
  keywords = "Cybersecurity, Privacy, Digital Rights, Drew"

  [params.author]
    email = "drew@x64.onl"
    name = "Drew"
    url = "https://drew.x64.onl"