baseURL = 'https://drew.x64.onl/'
languageCode = 'en-us'
title = "Drew's Space"
theme = 'drew.x64.onl'

[params]
  description = "Aloha World! I'm Drew: Jack of Cyber."
  keywords = "Drew, Jack of Cyber, Security Architect, Security Engineer, Cybersecurity, Information Security, Profolio, Blog"

  [params.author]
    email = "drew@x64.onl"
    name = "Drew"